package ec.com.smx.portal.rrhh.services.model;

import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the UsuarioRol service. Represents a row in the &quot;usuario_rol&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link ec.com.smx.portal.rrhh.services.model.impl.UsuarioRolModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ec.com.smx.portal.rrhh.services.model.impl.UsuarioRolImpl}.
 * </p>
 *
 * @author maballe
 * @see UsuarioRol
 * @see ec.com.smx.portal.rrhh.services.model.impl.UsuarioRolImpl
 * @see ec.com.smx.portal.rrhh.services.model.impl.UsuarioRolModelImpl
 * @generated
 */
public interface UsuarioRolModel extends BaseModel<UsuarioRol> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a usuario rol model instance should use the {@link UsuarioRol} interface instead.
     */

    /**
     * Returns the primary key of this usuario rol.
     *
     * @return the primary key of this usuario rol
     */
    public long getPrimaryKey();

    /**
     * Sets the primary key of this usuario rol.
     *
     * @param primaryKey the primary key of this usuario rol
     */
    public void setPrimaryKey(long primaryKey);

    /**
     * Returns the usuario rol ID of this usuario rol.
     *
     * @return the usuario rol ID of this usuario rol
     */
    public long getUsuarioRolId();

    /**
     * Sets the usuario rol ID of this usuario rol.
     *
     * @param UsuarioRolId the usuario rol ID of this usuario rol
     */
    public void setUsuarioRolId(long UsuarioRolId);

    /**
     * Returns the usuario ID of this usuario rol.
     *
     * @return the usuario ID of this usuario rol
     */
    public long getUsuarioId();

    /**
     * Sets the usuario ID of this usuario rol.
     *
     * @param usuarioId the usuario ID of this usuario rol
     */
    public void setUsuarioId(long usuarioId);

    /**
     * Returns the rol ID of this usuario rol.
     *
     * @return the rol ID of this usuario rol
     */
    public long getRolId();

    /**
     * Sets the rol ID of this usuario rol.
     *
     * @param rolId the rol ID of this usuario rol
     */
    public void setRolId(long rolId);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(
        ec.com.smx.portal.rrhh.services.model.UsuarioRol usuarioRol);

    @Override
    public int hashCode();

    @Override
    public CacheModel<ec.com.smx.portal.rrhh.services.model.UsuarioRol> toCacheModel();

    @Override
    public ec.com.smx.portal.rrhh.services.model.UsuarioRol toEscapedModel();

    @Override
    public ec.com.smx.portal.rrhh.services.model.UsuarioRol toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
