package ec.com.smx.portal.rrhh.services.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the Usuario service. Represents a row in the &quot;usuario&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link ec.com.smx.portal.rrhh.services.model.impl.UsuarioModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ec.com.smx.portal.rrhh.services.model.impl.UsuarioImpl}.
 * </p>
 *
 * @author maballe
 * @see Usuario
 * @see ec.com.smx.portal.rrhh.services.model.impl.UsuarioImpl
 * @see ec.com.smx.portal.rrhh.services.model.impl.UsuarioModelImpl
 * @generated
 */
public interface UsuarioModel extends BaseModel<Usuario> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a usuario model instance should use the {@link Usuario} interface instead.
     */

    /**
     * Returns the primary key of this usuario.
     *
     * @return the primary key of this usuario
     */
    public long getPrimaryKey();

    /**
     * Sets the primary key of this usuario.
     *
     * @param primaryKey the primary key of this usuario
     */
    public void setPrimaryKey(long primaryKey);

    /**
     * Returns the usuario ID of this usuario.
     *
     * @return the usuario ID of this usuario
     */
    public long getUsuarioId();

    /**
     * Sets the usuario ID of this usuario.
     *
     * @param usuarioId the usuario ID of this usuario
     */
    public void setUsuarioId(long usuarioId);

    /**
     * Returns the nombre of this usuario.
     *
     * @return the nombre of this usuario
     */
    @AutoEscape
    public String getNombre();

    /**
     * Sets the nombre of this usuario.
     *
     * @param nombre the nombre of this usuario
     */
    public void setNombre(String nombre);

    /**
     * Returns the role ID of this usuario.
     *
     * @return the role ID of this usuario
     */
    public long getRoleId();

    /**
     * Sets the role ID of this usuario.
     *
     * @param roleId the role ID of this usuario
     */
    public void setRoleId(long roleId);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(ec.com.smx.portal.rrhh.services.model.Usuario usuario);

    @Override
    public int hashCode();

    @Override
    public CacheModel<ec.com.smx.portal.rrhh.services.model.Usuario> toCacheModel();

    @Override
    public ec.com.smx.portal.rrhh.services.model.Usuario toEscapedModel();

    @Override
    public ec.com.smx.portal.rrhh.services.model.Usuario toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
