package ec.com.smx.portal.rrhh.services.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import ec.com.smx.portal.rrhh.services.model.UsuarioRol;
import ec.com.smx.portal.rrhh.services.service.UsuarioRolLocalServiceUtil;

/**
 * The extended model base implementation for the UsuarioRol service. Represents a row in the &quot;usuario_rol&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link UsuarioRolImpl}.
 * </p>
 *
 * @author maballe
 * @see UsuarioRolImpl
 * @see ec.com.smx.portal.rrhh.services.model.UsuarioRol
 * @generated
 */
public abstract class UsuarioRolBaseImpl extends UsuarioRolModelImpl
    implements UsuarioRol {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a usuario rol model instance should use the {@link UsuarioRol} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            UsuarioRolLocalServiceUtil.addUsuarioRol(this);
        } else {
            UsuarioRolLocalServiceUtil.updateUsuarioRol(this);
        }
    }
}
